a = int(input("Enter the first number : "))
b = int(input("Enter the second number : "))
print("addition of two numbers", a, "+", b, "is" , a+b)
print("subtraction of two numbers", a, "-", b, "is" , a-b)
print("multiplication of two numbers", a, "*", b, "is" , a*b)
print("division of two numbers", a, "/", b, "is" , a/b)
